services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  JanMikes\Slowpoker\TestTimeCommand: ~
  JanMikes\Slowpoker\FindSlowCommitCommand: ~

  Symfony\Component\Console\Application:
    arguments:
      - 'Slowpoker'
      - '0.1'
    calls:
      - [add, ['@JanMikes\Slowpoker\TestTimeCommand']]
      - [add, ['@JanMikes\Slowpoker\FindSlowCommitCommand']]
